---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# gtreg

<!-- badges: start -->
<!-- badges: end -->

This package provides the software tools to implement Gaussian Transform Regression introduced in "Gaussian transforms modeling and the estimation of distributional regression functions" Spady and Stouli (2020). 

With the tools in this package it is possible to obtain inference and estimation results for conditional distribution, quantile and density functions implied by flexible Gaussian representations.

For further details, please refer to the original text.

### Version 0.2.0

This version is purely a preliminary version!

- Imports all the required packages.
- Contains all the functions necessary to do get core results. __Functions have development names.__

## Installation

In order to install this package you need to use the Github version. Hopefully in the future a  version will be possible.

Following the steps below, you will be able to install the `gtreg` R package from GitHub, in each of R, R Studio, and Displayr.

The process is as follows:

1) Install and load the `devtools` package.

```
install.packages("devtools")
library(devtools)
```

2) Install the `gtreg` package using the Github repo location and load it.

```
install_github("diego-lda/gtreg")
library(gtreg)
```

All done!

## Style

In terms of style, to avoid confusion between objects and functions the soggested style that we will use is the underscore_separated convention.


